CREATE TABLE `a`.`posts` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `parentThread` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `textContent` VARCHAR(4095) NOT NULL,
  `imgURL` VARCHAR(45) NOT NULL,
  `IP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));